import type { Metadata } from "next";

import Footer from "./Components/Footer";
import Header from "./Components/Header";
import { UserProvider } from "./contexts/UserContext";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
         <UserProvider>
        <Header />
          {children}
        <Footer />
         </UserProvider>
      </body>
    </html>
  );
}
